export const emojiBanderas = [
    {
        id:"flag_1",
        emoticono:"🇪🇸",
    },
    {
        id:"flag_2",
        emoticono:"🇬🇧",
    },
    {
        id:"flag_3",
        emoticono:"🇫🇷",
    },
    {
        id:"flag_4",
        emoticono:"🇮🇹",
    },
    {
        id:"flag_5",
        emoticono:"🇩🇪",
    },
    {
        id:"flag_6",
        emoticono:"🇵🇹",
    },
    {
        id:"flag_7",
        emoticono:"🇷🇺",
    },
    {
        id:"flag_8",
        emoticono:"🇺🇸",
    },
    {
        id:"flag_9",
        emoticono:"🇨🇳",
    },
    {
        id:"flag_10",
        emoticono:"🇯🇵",
    },
    {
        id:"flag_11",
        emoticono:"🇰🇷",
    },
    {
        id:"flag_12",
        emoticono:"🇮🇳",
    },
    {
        id:"flag_13",
        emoticono:"🇦🇺",
    },
    {
        id:"flag_14",
        emoticono:"🇨🇦",
    },
    {
        id:"flag_15",
        emoticono:"🇲🇽",
    },
    {
        id:"flag_16",
        emoticono:"🇧🇷",
    },
    {
        id:"flag_17",
        emoticono:"🇦🇷",
    },
    {
        id:"flag_18",
        emoticono:"🇨🇱",
    },
    {
        id:"flag_19",
        emoticono:"🇨🇴",
    },
    {
        id:"flag_20",
        emoticono:"🇵🇪",
    },
    {
        id:"flag_21",
        emoticono:"🇻🇪",
    },
    {
        id:"flag_22",
        emoticono:"🇨🇷",
    },
];
