export const emojiBanderas = [
    {
        id:"pizza",
        emoticono:"🍕",
    },
    {
        id:"hamburguesa",
        emoticono:"🍔",
    },
    {
        id:"patatas_fritas",
        emoticono:"🍟",
    },
    {
        id:"perrito_caliente",
        emoticono:"🌭",
    },
    {
        id:"globo",
        emoticono:"🎈",
    },
    {
        id:"calabaza",
        emoticono:"🎃",
    },
    {
        id:"arbol_de_navidad",
        emoticono:"🎄",
    },
    {
        id:"emoji_cara_helada",
        emoticono:"🥶",
    },
    {
        id:"carrito_de_compras",
        emoticono:"🛒",
    },
    {
        id:"emoji_gafas_de_sol",
        emoticono:"😎",
    },
    {
        id:"emoji_corazon",
        emoticono:"😍",
    },
    {
        id:"emoji_cara_dinero",
        emoticono:"🤑",
    },
    {
        id:"emoji_cara_payaso",
        emoticono:"🤡",
    },
    {
        id:"emoji_cara_cowboy",
        emoticono:"🤠",
    },
    {
        id:"emoji_papa_noel",
        emoticono:"🎅",
    },
    {
        id:"policia",
        emoticono:"👮‍♂️",
    },
    {
        id:"coche",
        emoticono:"🚗",
    },
    {
        id:"coche_de_policia",
        emoticono:"🚓",
    },
    {
        id:"hambulancia",
        emoticono:"🚑",
    },
    {
        id:"bicicleta",
        emoticono:"🚲",
    },
    {
        id:"Nuke",
        emoticono:"☢",
    },
    {
        id:"reloj",
        emoticono:"🕓",
    },
];
